apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-7gaq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-rhtap-three-component-scenarios-7gaq
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-go-rhtap-three-component-scenarios-7gaq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-7gaq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-7gaq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ihaf-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-7gaq@sha256:a97575e755536127256cb97af55441707cc468f4c53c1e37e2050f78d544fe27
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
